contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #mosaicgermlinecallers channel"
    url: https://nfcore.slack.com/channels/mosaicgermlinecallers
    about: Discussion about the nf-core/mosaicgermlinecallers pipeline
